package admin

import (
	"context"
	"database/sql"
	"errors"
	"fmt"
)

var ErrNotFound = errors.New("resource not found")

type Repository struct{ db *sql.DB }
func NewRepository(db *sql.DB)*Repository{return &Repository{db:db}}
type User struct{ ID uint64; PublicID,Email,Name,Status string; Roles []string }
type Role struct{ ID uint64; Code,Name,Description string; IsSystem bool; Permissions []string }
type Permission struct{ Code,Name,Description string }
type Menu struct{ ID uint64; PublicID string; ParentID sql.NullInt64; Code,Name string; Route,Icon,PermissionCode sql.NullString; SortOrder int; Active bool }

func(r *Repository)ListUsers(ctx context.Context)([]User,error){rows,err:=r.db.QueryContext(ctx,`SELECT id,public_id,email,name,status FROM users ORDER BY id DESC`);if err!=nil{return nil,err};defer rows.Close();var out []User;for rows.Next(){var u User;if err:=rows.Scan(&u.ID,&u.PublicID,&u.Email,&u.Name,&u.Status);err!=nil{return nil,err};roles,err:=r.roleCodesForUser(ctx,u.ID);if err!=nil{return nil,err};u.Roles=roles;out=append(out,u)};return out,rows.Err()}
func(r *Repository)roleCodesForUser(ctx context.Context,id uint64)([]string,error){rows,err:=r.db.QueryContext(ctx,`SELECT r.code FROM roles r JOIN user_roles ur ON ur.role_id=r.id WHERE ur.user_id=? ORDER BY r.code`,id);if err!=nil{return nil,err};defer rows.Close();var v []string;for rows.Next(){var s string;if err:=rows.Scan(&s);err!=nil{return nil,err};v=append(v,s)};return v,rows.Err()}
func(r *Repository)CreateUser(ctx context.Context,publicID,email,name,passwordHash,status string,roleCodes []string)error{return r.withTx(ctx,func(tx *sql.Tx)error{res,err:=tx.ExecContext(ctx,`INSERT INTO users(public_id,email,name,password_hash,status) VALUES(?,?,?,?,?)`,publicID,email,name,passwordHash,status);if err!=nil{return err};id,err:=res.LastInsertId();if err!=nil{return err};return assignRoles(ctx,tx,uint64(id),roleCodes)})}
func(r *Repository)UpdateUser(ctx context.Context,publicID,email,name,status string,roleCodes []string)error{return r.withTx(ctx,func(tx *sql.Tx)error{res,err:=tx.ExecContext(ctx,`UPDATE users SET email=?,name=?,status=? WHERE public_id=?`,email,name,status,publicID);if err!=nil{return err};n,_:=res.RowsAffected();if n==0{return ErrNotFound};var id uint64;if err:=tx.QueryRowContext(ctx,`SELECT id FROM users WHERE public_id=?`,publicID).Scan(&id);err!=nil{return err};if _,err:=tx.ExecContext(ctx,`DELETE FROM user_roles WHERE user_id=?`,id);err!=nil{return err};return assignRoles(ctx,tx,id,roleCodes)})}
func assignRoles(ctx context.Context,tx *sql.Tx,userID uint64,codes []string)error{for _,code:=range codes{res,err:=tx.ExecContext(ctx,`INSERT INTO user_roles(user_id,role_id) SELECT ?,id FROM roles WHERE code=?`,userID,code);if err!=nil{return err};n,_:=res.RowsAffected();if n==0{return fmt.Errorf("%w: role %s",ErrNotFound,code)}};return nil}

func(r *Repository)ListRoles(ctx context.Context)([]Role,error){rows,err:=r.db.QueryContext(ctx,`SELECT id,code,name,COALESCE(description,''),is_system FROM roles ORDER BY name`);if err!=nil{return nil,err};defer rows.Close();var out []Role;for rows.Next(){var x Role;if err:=rows.Scan(&x.ID,&x.Code,&x.Name,&x.Description,&x.IsSystem);err!=nil{return nil,err};p,err:=r.permissionCodesForRole(ctx,x.ID);if err!=nil{return nil,err};x.Permissions=p;out=append(out,x)};return out,rows.Err()}
func(r *Repository)permissionCodesForRole(ctx context.Context,id uint64)([]string,error){rows,err:=r.db.QueryContext(ctx,`SELECT p.code FROM permissions p JOIN role_permissions rp ON rp.permission_id=p.id WHERE rp.role_id=? ORDER BY p.code`,id);if err!=nil{return nil,err};defer rows.Close();var v []string;for rows.Next(){var s string;if err:=rows.Scan(&s);err!=nil{return nil,err};v=append(v,s)};return v,rows.Err()}
func(r *Repository)ListPermissions(ctx context.Context)([]Permission,error){rows,err:=r.db.QueryContext(ctx,`SELECT code,name,COALESCE(description,'') FROM permissions ORDER BY code`);if err!=nil{return nil,err};defer rows.Close();var out []Permission;for rows.Next(){var x Permission;if err:=rows.Scan(&x.Code,&x.Name,&x.Description);err!=nil{return nil,err};out=append(out,x)};return out,rows.Err()}
func(r *Repository)CreateRole(ctx context.Context,code,name,description string,permissions []string)error{return r.withTx(ctx,func(tx *sql.Tx)error{res,err:=tx.ExecContext(ctx,`INSERT INTO roles(code,name,description) VALUES(?,?,?)`,code,name,description);if err!=nil{return err};id,_:=res.LastInsertId();return assignPermissions(ctx,tx,uint64(id),permissions)})}
func(r *Repository)UpdateRole(ctx context.Context,code,name,description string,permissions []string)error{return r.withTx(ctx,func(tx *sql.Tx)error{var id uint64;err:=tx.QueryRowContext(ctx,`SELECT id FROM roles WHERE code=?`,code).Scan(&id);if errors.Is(err,sql.ErrNoRows){return ErrNotFound};if err!=nil{return err};if _,err:=tx.ExecContext(ctx,`UPDATE roles SET name=?,description=? WHERE id=?`,name,description,id);err!=nil{return err};if _,err:=tx.ExecContext(ctx,`DELETE FROM role_permissions WHERE role_id=?`,id);err!=nil{return err};return assignPermissions(ctx,tx,id,permissions)})}
func assignPermissions(ctx context.Context,tx *sql.Tx,roleID uint64,codes []string)error{for _,code:=range codes{res,err:=tx.ExecContext(ctx,`INSERT INTO role_permissions(role_id,permission_id) SELECT ?,id FROM permissions WHERE code=?`,roleID,code);if err!=nil{return err};n,_:=res.RowsAffected();if n==0{return fmt.Errorf("%w: permission %s",ErrNotFound,code)}};return nil}
func(r *Repository)ListMenus(ctx context.Context)([]Menu,error){rows,err:=r.db.QueryContext(ctx,`SELECT id,public_id,parent_id,code,name,route,icon,permission_code,sort_order,is_active FROM menus ORDER BY COALESCE(parent_id,0),sort_order,id`);if err!=nil{return nil,err};defer rows.Close();var out []Menu;for rows.Next(){var x Menu;if err:=rows.Scan(&x.ID,&x.PublicID,&x.ParentID,&x.Code,&x.Name,&x.Route,&x.Icon,&x.PermissionCode,&x.SortOrder,&x.Active);err!=nil{return nil,err};out=append(out,x)};return out,rows.Err()}
func(r *Repository)CreateMenu(ctx context.Context,publicID string,parentID *uint64,code,name string,route,icon,permission *string,sort int,active bool)error{_,err:=r.db.ExecContext(ctx,`INSERT INTO menus(public_id,parent_id,code,name,route,icon,permission_code,sort_order,is_active) VALUES(?,?,?,?,?,?,?,?,?)`,publicID,parentID,code,name,route,icon,permission,sort,active);return err}
func(r *Repository)UpdateMenu(ctx context.Context,publicID string,parentID *uint64,name string,route,icon,permission *string,sort int,active bool)error{res,err:=r.db.ExecContext(ctx,`UPDATE menus SET parent_id=?,name=?,route=?,icon=?,permission_code=?,sort_order=?,is_active=? WHERE public_id=?`,parentID,name,route,icon,permission,sort,active,publicID);if err!=nil{return err};n,_:=res.RowsAffected();if n==0{return ErrNotFound};return nil}
func(r *Repository)withTx(ctx context.Context,fn func(*sql.Tx)error)error{tx,err:=r.db.BeginTx(ctx,nil);if err!=nil{return err};if err:=fn(tx);err!=nil{_ = tx.Rollback();return err};return tx.Commit()}
